const MODE_UPDATE = 'MODE_UPDATE';
const ACTIVITY_UPDATE = 'ACTIVITY_UPDATE';
const ANNOTATIONS_CREATE = 'ANNOTATIONS_CREATE';
const ANNOTATIONS_UPDATE_LAST = 'ANNOTATIONS_UPDATE_LAST';
const ANNOTATIONS_RESET = 'ANNOTATIONS_RESET';
const ZOOM_UPDATE = 'ZOOM_UPDATE';
const INITIALIZE = 'INITIALIZE';

export {
  MODE_UPDATE,
  ACTIVITY_UPDATE,
  ANNOTATIONS_CREATE,
  ANNOTATIONS_UPDATE_LAST,
  ANNOTATIONS_RESET,
  ZOOM_UPDATE,
  INITIALIZE,
};
