const types = {
  MODE_UPDATE: 'MODE_UPDATE',
  ACTIVITY_UPDATE: 'ACTIVITY_UPDATE',
  ANNOTATIONS_CREATE: 'ANNOTATIONS_CREATE',
  ANNOTATIONS_UPDATE_LAST: 'ANNOTATIONS_UPDATE_LAST',
  ANNOTATIONS_RESET: 'ANNOTATIONS_RESET',
};

export default types;
