export const MODE_UPDATE = 'MODE_UPDATE';
export const ACTIVITY_UPDATE = 'ACTIVITY_UPDATE';
export const ANNOTATIONS_CREATE = 'ANNOTATIONS_CREATE';
export const ANNOTATIONS_UPDATE_LAST = 'ANNOTATIONS_UPDATE_LAST';
export const ANNOTATIONS_RESET = 'ANNOTATIONS_RESET';
export const ZOOM_UPDATE = 'ZOOM_UPDATE';
export const INITIALIZE = 'INITIALIZE';
